config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'followings'
      get 'followers'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :favorites
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :micropost
  belongs_to :user

  validates :user_id, presence: true
  validates :micropost_id, presence: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :logged_in_user, only: [:create]
  before_action :set_micropost, only: [:create]
  before_action :check_micropost, only: [:create]

  def show
    @user = User.find(params[:id])
    @favorite_microposts = @user.favorite_microposts
    # @favorites = @user.favorites #.order(created_at: :desc)
  end


  def create
    current_user.like(@micropost)
    flash[:success] = "お気に入りに追加しました！"
    redirect_to root_url
  end

  def destroy
    # @micropost = Micropost.find(params[:favorite][:micropost_id])
    # current_user.unlike(@micropost)
    @favorite = Favorite.find(params[:id])
    @favorite.destroy if @favorite.present?
    flash[:success] = "お気に入りを削除しました！"
    redirect_to root_url
  end
  
  def set_micropost
    @micropost = Micropost.find(params[:micropost_id])
  end
  
  def check_micropost
    redirect_to root_url if @micropost.user_id == current_user.id
  end

  # private
  # def favorite_params
  #   params.require(:favorite).permit(:user_id, :micropost_id)
  # end
end

app/views/favorites/_favorites.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/favorites/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1 class="clearfix">
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <div><%= link_to 'フォロワー一覧', followers_user_path(@user) %></div>
      <div><%= link_to 'フォローしている人の一覧', followings_user_path(@user) %></div>
    </section>

    <div class="panel panel-info">
      <div class="panel-heading">
          <h5 class="panel-title" id="panel-title">Name</h5>
      </div>
      <div class="panel-body">
          <%= @user.name %>(<%= link_to "編集" , edit_user_path(@user.id) %>)
      </div>
  
      <div class="panel-heading">
          <h5 class="panel-title" id="panel-title">Email</h5>
      </div>
      <div class="panel-body">
          <%= @user.email %>
      </div>
  
      <div class="panel-heading">
          <h5 class="panel-title" id="panel-title">Prefectures</h5>
      </div>
      <div class="panel-body">
          <%= @user.prefectures_code %>
      </div>
  
      <div class="panel-heading">
          <h5 class="panel-title" id="panel-title">Profile</h5>
      </div>
      <div class="panel-body">
          <%= @user.profile %>
      </div>
    </div>

  </aside>
  <div class="col-md-8">
    <% if @favorite_microposts.present? %>
      <h3>Favorites (<%= @favorite_microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @favorite_microposts %>
      </ol>
    <% end %>
  </div>
</div>